<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ValidationFormRequest extends FormRequest
{
    /* Sirve para redirigir en caso de error a otro lugar  */
    //protected $redirect = '/dashboard';

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nombre' => 'required|max:15',
            'descrip' => 'required',
        ];
    }

    public function messages()
    {
        //return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'nombre.required' => 'El nombre es obligatorio',
            'descrip.required' => 'La descripción es obligatoria'
        ];
    }


}
